/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Ivan Leonardo R
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        VentanaPedidos.setVisible(false);
        VentanaSolicitudes.setVisible(false);
        VentanaResultados.setVisible(false);
        
        //Ventana de pedidos
        NombrePedidos.setVisible(false);
        NombreID.setVisible(false);
        IDPedido.setVisible(false);
        NombreRutaElegir.setVisible(false);
        TipoDeRuta.setVisible(false);
        NombreMaxCamiones.setVisible(false);
        CantMaxCamiones.setVisible(false);
        AgregarPedido.setVisible(false);
        
        //Ventana para realizar solicitud
        NombreSolicitud.setVisible(false);
        NombreSelecPedido.setVisible(false);
        TipoDePedido.setVisible(false);
        NombreRutaATomar.setVisible(false);
        SeleccionarRuta.setVisible(false);
        NombreCamUSar.setVisible(false);
        CamionesSolicitados.setVisible(false);
        SolicitarPedido.setVisible(false);
        
        //Ventana de resultados
        jScrollPane1.setVisible(false);
        ResultadoSolicitudes.setVisible(false);
        NombreRutasResultados.setVisible(false);
        NombrePedidosResultados.setVisible(false);
        RutaParaResultados.setVisible(false);
        PedidosParaResultados.setVisible(false);
        BuscarResultados.setVisible(false);
        Resultado1.setVisible(false);
        Resultado2.setVisible(false);
        Resultado3.setVisible(false);
        Resultado4.setVisible(false);
        jSeparator1.setVisible(false);
        CamDispRuta.setVisible(false);
        CamMaxPorPedido.setVisible(false);
        UsoCamiones.setVisible(false);
        CamFaltantes.setVisible(false);
        Salida.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        IniciarPrograma = new javax.swing.JButton();
        Icono = new javax.swing.JLabel();
        NombreRuta = new javax.swing.JLabel();
        RutaCreada = new javax.swing.JTextField();
        NombreCantidadCamion = new javax.swing.JLabel();
        CantCamionesPorRuta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaRutas = new javax.swing.JTextArea();
        AgregarRuta = new javax.swing.JButton();
        VentanaRutas = new javax.swing.JLabel();
        NombrePedidos = new javax.swing.JLabel();
        NombreID = new javax.swing.JLabel();
        IDPedido = new javax.swing.JTextField();
        NombreRutaElegir = new javax.swing.JLabel();
        TipoDeRuta = new javax.swing.JComboBox<>();
        NombreMaxCamiones = new javax.swing.JLabel();
        CantMaxCamiones = new javax.swing.JTextField();
        AgregarPedido = new javax.swing.JButton();
        VentanaPedidos = new javax.swing.JLabel();
        NombreSolicitud = new javax.swing.JLabel();
        NombreSelecPedido = new javax.swing.JLabel();
        TipoDePedido = new javax.swing.JComboBox<>();
        NombreRutaATomar = new javax.swing.JLabel();
        SeleccionarRuta = new javax.swing.JComboBox<>();
        NombreCamUSar = new javax.swing.JLabel();
        CamionesSolicitados = new javax.swing.JTextField();
        SolicitarPedido = new javax.swing.JButton();
        VentanaSolicitudes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultadoSolicitudes = new javax.swing.JTextArea();
        Resultado1 = new javax.swing.JLabel();
        Resultado2 = new javax.swing.JLabel();
        Resultado3 = new javax.swing.JLabel();
        Resultado4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NombreRutasResultados = new javax.swing.JLabel();
        NombrePedidosResultados = new javax.swing.JLabel();
        RutaParaResultados = new javax.swing.JComboBox<>();
        PedidosParaResultados = new javax.swing.JComboBox<>();
        BuscarResultados = new javax.swing.JButton();
        CamDispRuta = new javax.swing.JTextField();
        CamMaxPorPedido = new javax.swing.JTextField();
        UsoCamiones = new javax.swing.JTextField();
        CamFaltantes = new javax.swing.JTextField();
        Salida = new javax.swing.JButton();
        VentanaResultados = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IniciarPrograma.setBackground(new java.awt.Color(0, 255, 102));
        IniciarPrograma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IniciarPrograma.setText("Iniciar");
        IniciarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarProgramaActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen_3.png"))); // NOI18N
        getContentPane().add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 180, 160));

        NombreRuta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreRuta.setForeground(new java.awt.Color(255, 255, 255));
        NombreRuta.setText("Nombre de la ruta :");
        getContentPane().add(NombreRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        RutaCreada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaCreadaActionPerformed(evt);
            }
        });
        getContentPane().add(RutaCreada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 70, 20));

        NombreCantidadCamion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreCantidadCamion.setForeground(new java.awt.Color(255, 255, 255));
        NombreCantidadCamion.setText("Cantidad de camiones por ruta :");
        getContentPane().add(NombreCantidadCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        getContentPane().add(CantCamionesPorRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 70, 20));

        ListaRutas.setColumns(20);
        ListaRutas.setRows(5);
        jScrollPane2.setViewportView(ListaRutas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 390, 130));

        AgregarRuta.setBackground(new java.awt.Color(0, 255, 255));
        AgregarRuta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgregarRuta.setText("Agregar");
        getContentPane().add(AgregarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 90, -1));

        VentanaRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Colo_1.jpg"))); // NOI18N
        getContentPane().add(VentanaRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 260));

        NombrePedidos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NombrePedidos.setForeground(new java.awt.Color(255, 255, 255));
        NombrePedidos.setText("Crear pedidos");
        getContentPane().add(NombrePedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        NombreID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreID.setForeground(new java.awt.Color(255, 255, 255));
        NombreID.setText("ID del pedido :");
        getContentPane().add(NombreID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        getContentPane().add(IDPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 50, 20));

        NombreRutaElegir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreRutaElegir.setForeground(new java.awt.Color(255, 255, 255));
        NombreRutaElegir.setText("Tipo de ruta a elegir :");
        getContentPane().add(NombreRutaElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        TipoDeRuta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TipoDeRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(TipoDeRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 90, -1));

        NombreMaxCamiones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreMaxCamiones.setForeground(new java.awt.Color(255, 255, 255));
        NombreMaxCamiones.setText("Cantidad max de camiones :");
        getContentPane().add(NombreMaxCamiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));
        getContentPane().add(CantMaxCamiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 50, -1));

        AgregarPedido.setBackground(new java.awt.Color(0, 255, 255));
        AgregarPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgregarPedido.setText("Agregar");
        getContentPane().add(AgregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        VentanaPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Colo_1.jpg"))); // NOI18N
        getContentPane().add(VentanaPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 350, 250));

        NombreSolicitud.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NombreSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        NombreSolicitud.setText("Realizar solicitud");
        getContentPane().add(NombreSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        NombreSelecPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreSelecPedido.setForeground(new java.awt.Color(255, 255, 255));
        NombreSelecPedido.setText("Seleccionar pedido :");
        getContentPane().add(NombreSelecPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        TipoDePedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TipoDePedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(TipoDePedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 80, -1));

        NombreRutaATomar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreRutaATomar.setForeground(new java.awt.Color(255, 255, 255));
        NombreRutaATomar.setText("Seleccionar ruta a tomar :");
        getContentPane().add(NombreRutaATomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        SeleccionarRuta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SeleccionarRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(SeleccionarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 80, -1));

        NombreCamUSar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreCamUSar.setForeground(new java.awt.Color(255, 255, 255));
        NombreCamUSar.setText("Cantidad de camiones a usar :");
        getContentPane().add(NombreCamUSar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));
        getContentPane().add(CamionesSolicitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 70, -1));

        SolicitarPedido.setBackground(new java.awt.Color(0, 255, 255));
        SolicitarPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SolicitarPedido.setText("Solicitar");
        getContentPane().add(SolicitarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        VentanaSolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Colo_1.jpg"))); // NOI18N
        getContentPane().add(VentanaSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 350, 250));

        ResultadoSolicitudes.setColumns(20);
        ResultadoSolicitudes.setRows(5);
        jScrollPane1.setViewportView(ResultadoSolicitudes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 310, 130));

        Resultado1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Resultado1.setForeground(new java.awt.Color(255, 255, 255));
        Resultado1.setText("Camiones disponibles por ruta :");
        getContentPane().add(Resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, -1, -1));

        Resultado2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Resultado2.setForeground(new java.awt.Color(255, 255, 255));
        Resultado2.setText("Cantidad max de camiones por pedido :");
        getContentPane().add(Resultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, -1, -1));

        Resultado3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Resultado3.setForeground(new java.awt.Color(255, 255, 255));
        Resultado3.setText("Uso de los camiones :");
        getContentPane().add(Resultado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 820, -1, -1));

        Resultado4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Resultado4.setForeground(new java.awt.Color(255, 255, 255));
        Resultado4.setText("Camiones que hacen falta :");
        getContentPane().add(Resultado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 860, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 732, 10, 170));

        NombreRutasResultados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreRutasResultados.setForeground(new java.awt.Color(255, 255, 255));
        NombreRutasResultados.setText("Rutas");
        getContentPane().add(NombreRutasResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, -1, -1));

        NombrePedidosResultados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombrePedidosResultados.setForeground(new java.awt.Color(255, 255, 255));
        NombrePedidosResultados.setText("Pedidos");
        getContentPane().add(NombrePedidosResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        RutaParaResultados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RutaParaResultados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(RutaParaResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, -1, -1));

        PedidosParaResultados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PedidosParaResultados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(PedidosParaResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, -1, -1));

        BuscarResultados.setBackground(new java.awt.Color(0, 255, 255));
        BuscarResultados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BuscarResultados.setText("Buscar");
        getContentPane().add(BuscarResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, -1, -1));
        getContentPane().add(CamDispRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 740, 60, -1));
        getContentPane().add(CamMaxPorPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 780, 60, -1));
        getContentPane().add(UsoCamiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 820, 60, -1));
        getContentPane().add(CamFaltantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 860, 60, -1));

        Salida.setBackground(new java.awt.Color(255, 102, 102));
        Salida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salida.setText("Salir");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        getContentPane().add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 870, -1, -1));

        VentanaResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Colo_1.jpg"))); // NOI18N
        getContentPane().add(VentanaResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 710, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarProgramaActionPerformed
        
        //Ventana de crear rutas
        NombreRuta.setVisible(false);
        RutaCreada.setVisible(false);
        NombreCantidadCamion.setVisible(false);
        CantCamionesPorRuta.setVisible(false);
        jScrollPane2.setVisible(false);
        ListaRutas.setVisible(false);
        AgregarRuta.setVisible(false);
        IniciarPrograma.setVisible(false);
        
        
        
        //Ventana de pedidos
        VentanaPedidos.setVisible(true);
        NombrePedidos.setVisible(true);
        NombreID.setVisible(true);
        IDPedido.setVisible(true);
        NombreRutaElegir.setVisible(true);
        TipoDeRuta.setVisible(true);
        NombreMaxCamiones.setVisible(true);
        CantMaxCamiones.setVisible(true);
        AgregarPedido.setVisible(true);

        //Ventana de solicitudes
        VentanaSolicitudes.setVisible(true);
        NombreSolicitud.setVisible(true);
        NombreSelecPedido.setVisible(true);
        TipoDePedido.setVisible(true);
        NombreRutaATomar.setVisible(true);
        SeleccionarRuta.setVisible(true);
        NombreCamUSar.setVisible(true);
        CamionesSolicitados.setVisible(true);
        SolicitarPedido.setVisible(true);
        
        //Ventana de resultados
        VentanaResultados.setVisible(true);
        jScrollPane1.setVisible(true);
        ResultadoSolicitudes.setVisible(true);
        NombreRutasResultados.setVisible(true);
        NombrePedidosResultados.setVisible(true);
        RutaParaResultados.setVisible(true);
        PedidosParaResultados.setVisible(true);
        BuscarResultados.setVisible(true);
        Resultado1.setVisible(true);
        Resultado2.setVisible(true);
        Resultado3.setVisible(true);
        Resultado4.setVisible(true);
        jSeparator1.setVisible(true);
        CamDispRuta.setVisible(true);
        CamMaxPorPedido.setVisible(true);
        UsoCamiones.setVisible(true);
        CamFaltantes.setVisible(true);
        Salida.setVisible(true);
        
    }//GEN-LAST:event_IniciarProgramaActionPerformed

    private void RutaCreadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaCreadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutaCreadaActionPerformed

    private void AgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarRutaActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarPedido;
    private javax.swing.JButton AgregarRuta;
    private javax.swing.JButton BuscarResultados;
    private javax.swing.JTextField CamDispRuta;
    private javax.swing.JTextField CamFaltantes;
    private javax.swing.JTextField CamMaxPorPedido;
    private javax.swing.JTextField CamionesSolicitados;
    private javax.swing.JTextField CantCamionesPorRuta;
    private javax.swing.JTextField CantMaxCamiones;
    private javax.swing.JTextField IDPedido;
    private javax.swing.JLabel Icono;
    private javax.swing.JButton IniciarPrograma;
    private javax.swing.JTextArea ListaRutas;
    private javax.swing.JLabel NombreCamUSar;
    private javax.swing.JLabel NombreCantidadCamion;
    private javax.swing.JLabel NombreID;
    private javax.swing.JLabel NombreMaxCamiones;
    private javax.swing.JLabel NombrePedidos;
    private javax.swing.JLabel NombrePedidosResultados;
    private javax.swing.JLabel NombreRuta;
    private javax.swing.JLabel NombreRutaATomar;
    private javax.swing.JLabel NombreRutaElegir;
    private javax.swing.JLabel NombreRutasResultados;
    private javax.swing.JLabel NombreSelecPedido;
    private javax.swing.JLabel NombreSolicitud;
    private javax.swing.JComboBox<String> PedidosParaResultados;
    private javax.swing.JLabel Resultado1;
    private javax.swing.JLabel Resultado2;
    private javax.swing.JLabel Resultado3;
    private javax.swing.JLabel Resultado4;
    private javax.swing.JTextArea ResultadoSolicitudes;
    private javax.swing.JTextField RutaCreada;
    private javax.swing.JComboBox<String> RutaParaResultados;
    private javax.swing.JButton Salida;
    private javax.swing.JComboBox<String> SeleccionarRuta;
    private javax.swing.JButton SolicitarPedido;
    private javax.swing.JComboBox<String> TipoDePedido;
    private javax.swing.JComboBox<String> TipoDeRuta;
    private javax.swing.JTextField UsoCamiones;
    private javax.swing.JLabel VentanaPedidos;
    private javax.swing.JLabel VentanaResultados;
    private javax.swing.JLabel VentanaRutas;
    private javax.swing.JLabel VentanaSolicitudes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
